### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by dinosw** [Zoltanar/Happy-Search#4]
Hi

I have discovered a bug.
I am unable to remove something from my Wishlist, from the right click menu.
When selecting Wishlist-->None, it results in an error, saying that "None" doesn't exist.
Additionally, I can see that other titles which aren't on my wishlist, doesn't use the value "None", but rather the value "Null".
![happy search_-_2017-04-19_-_00-28-53](https://cloud.githubusercontent.com/assets/7477309/25156038/92c37caa-2498-11e7-90d0-b6c2a6be60a1.png)

Kind Regards
Steven Windfeld

**Comment by Zoltanar** [comment]
I'm aware of this issue and it has been solved but I haven't had the time to get a release out.
In the meantime, you will have to do it in the VNDB page (which you can open via clicking the ID in VN tabs).
Thanks for the feedback.

**Comment by dinosw** [comment]
Thank you for the quick reply.
I know I can do it on VNDB, I just had a bunch which was on my userlist and wishlist, so I thought I could do it in one fell swoop.
Alas, I ended up doing it one by one :)
Again, thank you for your continued effort 👍 

Btw.
I had been meaning to ask you, if it would also be possible to add an option regarding the use of stable / unstable updates.
I always use the latest, therefore whenever I open Happy Search, it warns be that the latest stable version is 1.7.0 (as I recall). It would be great, if there was a simple option to, where I could select that I am using the unstable branch, and if it would then check my version against this instead.

**Comment by Zoltanar** [comment]
Issue has been fixed so it will be in next release. Regarding the latest stable release pop-up, you can disable it by running with parameter -sc. To do this, make a shortcut to Happy search.exe, go to the shortcut properties, and add -sc to the end of the text in Target.

**Comment by dinosw** [comment]
Thanks 👍
