### ISSUE TITLE
Producers list

### ISSUE THREAD

**Issue by dinosw** [Zoltanar/Happy-Search#5]
Hi

Could you perhaps change the name of the Producers list to Publishers list.
For instance, Sekai Project does not produce visual novels, they publish translations of visual novels. The term producer isn't used on VNDB either, they use the terms developer and publisher instead.

I know it is a minor detail, but I hope you will consider it :)

**Comment by Zoltanar** [comment]
The program uses the developer of the first non-trial release to determine the developer (which I use the word Producer for), this is described in the Help dialogs launched by yellow buttons.  
  
Searching for titles by producer called Sekai Project should not bring any results (and it doesn't in the current build).  
  
There is no notion of Publishers in the program, only developers, however, some titles may only have a publisher and no developer, in which case, the 'Producer' will be the publisher.

**Comment by dinosw** [comment]
Thank you for the explanation
