### ISSUE TITLE
Release of bugfix

### ISSUE THREAD

**Issue by dinosw** [Zoltanar/Happy-Search#6]
Hi

In [issue#4](https://github.com/Zoltanar/Happy-Search/issues/4) you mentioned that you had fixed the bug in question, but had yet to release the bugfix.
Do you have an estimate for when it will be released?

**Comment by Zoltanar** [comment]
I have not had much time to work on this project in the recent months, and the current build has broken features (due to a big overhaul in filtering), I can post that build if you want, as for a fully functional release, I have no estimate for when that will be.

**Comment by dinosw** [comment]
I'll wait for the finished build :)
Keep up the good work, and do not let my questions stress you or anything.
Thank you again for the app :)

**Comment by Zoltanar** [comment]
Just released a new build (supposed to be fully functional) which includes this fix.
